### ISSUE TITLE
兄弟，可否加个功能，multiSet/multiSetHeader，用于一次设置多个值set或者多个setHeader。

### ISSUE THREAD

**Issue by nottellyou** [jshensh/php-curl-class#4]
兄弟，可否加个功能，multiSet/multiSetHeader，用于一次设置多个值set或者多个setHeader。

场景原因：
我有这样一个场景：获取远程图片，有些网站的图片需要加referer，而且这个referer是它的主站的域名(图片域名用的是另外一个域名，和微信公众号有点相似)，加ua；有些网站不需要加referer；有些网站主域名不需要加，但子域名需要加referer；情况很复杂。
我可以根据域名输出一个需要的数组，此数组可以为空，为空表示不用加任何信息可直接获取此图片。

现状：
Client::init($url)->set()->set()->set()->set()->exec();

期望结果：
Client::init($url)->multiSet($arr)->exec();

**Comment by jshensh** [comment]
已经有数组的话，这边推荐用 `foreach` 操作会方便一些。。

**Comment by nottellyou** [comment]
我自个加上去算了。

**Comment by jshensh** [comment]
> 我自个加上去算了。

https://github.com/jshensh/php-curl-class#%E8%AE%BE%E7%BD%AE%E8%AF%B7%E6%B1%82%E7%AD%BE%E5%90%8D%E4%BB%A5%E5%BE%AE%E4%BF%A1%E6%94%AF%E4%BB%98%E4%B8%BA%E4%BE%8B
给 client 添加自定义方法的话参考这个就可以了

**Comment by nottellyou** [comment]
好的，多谢
